const officeEquipmentEnum = [
  "Laptop Stand",
  "Cable Management Solutions",
  "Mouse and Keyboard Wrist Rests",
  "Document Holder",
  "Multi-Outlet Power Strip",
  "Drawer Organizers",  
  "Standing Desk Converter",
  "Adjustable Monitor Stand",
  "Blue Light Blocking Glasses",
  "Desk Calendar or Planner",
  "Wall Clock",
  "File Cabinet or File Organizer",
  "Desk Fan",
  "Air Purifier",
  "Portable Speaker",
  "USB Hub",
  "Noise-Canceling Headphones",
  "Desk Lamp with Adjustable Brightness",
  "Laptop Docking Station",
  "Phone Stand with Charger",
  "Portable Whiteboard or Notepad",
  "Ergonomic Footrest",
  "Privacy Screen for Laptop",
  "Cable Clips and Holders",
  "Portable Laptop Battery Pack",
  "Wireless Charging Pad",
  "External Hard Drive",
  "Desk Drawer Lock",
  "Monitor Privacy Filter",
  "Wireless Keyboard and Mouse",
  "Desk Cable Tray",
  "Smartphone/Tablet Stand",
  "Adjustable Desk Legs",
  "Coffee Cup Warmer",
  "Desk-mounted Task Light",
  "Wireless Presenter",
  "Desk-mounted Power Hub",
  "USB-C Adapter",
  "Desktop Document Scanner",
  "Filing Cabinet Lock",
  "Monitor Arm with Gas Spring",
  "Keyboard Cover",
  "Wireless Printer",
  "Ergonomic Chair Cushion",
  "Tabletop Cable Grommet",
  "Desk Drawer Organizer Tray",
  "Portable External Monitor",
  "Laptop Privacy Filter",
  "Adjustable Laptop Cooling Pad",
  "Monitor Stand with Built-in Storage"
];

export { officeEquipmentEnum };
